# Generated by Django 4.2 on 2026-01-29 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gas_type', models.CharField(max_length=20)),
                ('forecasted_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('iot_internship', 'Internship'), ('workshop', 'Workshop'), ('vision', 'Vision & Mission'), ('project', 'Projects'), ('research', 'Research & Publications'), ('Brochure', 'Brochure'), ('', '')], max_length=50)),
                ('file', models.FileField(upload_to='brochures/%Y/%m/%d/')),
                ('icon', models.CharField(default='📄', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='The text to display in the scroll bar', max_length=255)),
                ('start_date', models.DateTimeField(help_text='When to start showing this message')),
                ('end_date', models.DateTimeField(help_text='When to stop showing this message')),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Check this for annual events (e.g., Independence Day). The year will be ignored.')),
                ('link', models.CharField(blank=True, help_text='Optional link to a registration page or brochure', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique URL ID (e.g. 'indoor-monitor')", max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Air Quality', 'Air Quality'), ('Water Solutions', 'Water Solutions'), ('Weather', 'Weather'), ('Training', 'Training')], default='Air Quality', max_length=50)),
                ('image', models.ImageField(upload_to='products/hero/')),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='products/sub/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='products/brochures/')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('brochure', 'Brochure'), ('poster', 'Poster'), ('slide', 'Slide'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('sl_no', models.AutoField(db_column='sl_no', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='submitted_at')),
            ],
            options={
                'db_table': 'support',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_login',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkshopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Hands-on-Workshop', 'Hands-on Workshop'), ('Summer Internship', 'Summer Internship'), ('Value Added Course', 'Value Added Course'), ('Workshop', 'Workshop'), ('Research', 'Research')], default='Workshop', max_length=50)),
                ('duration', models.CharField(blank=True, help_text="e.g. '1 Day', '15 Days'", max_length=50)),
                ('event_date_text', models.CharField(help_text="e.g. 'March 19, 2025'", max_length=100)),
                ('participants', models.CharField(blank=True, help_text="e.g. '40 Participants'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('brochure_file', models.FileField(blank=True, null=True, upload_to='workshops/brochures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_key', models.CharField(max_length=100)),
                ('spec_value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='⚡', help_text='Paste an Emoji here', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='HealthQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.signup')),
            ],
        ),
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('respiratory_conditions', models.JSONField(blank=True, default=list)),
                ('smoking_history', models.TextField(blank=True, null=True)),
                ('living_environment', models.JSONField(blank=True, default=list)),
                ('common_symptoms', models.JSONField(blank=True, default=list)),
                ('occupational_exposure', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_history', models.JSONField(blank=True, default=list)),
                ('health_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='health_assessment', to='myapp.signup')),
            ],
            options={
                'db_table': 'health_assessment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('relationship', models.CharField(max_length=50)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='myapp.signup')),
            ],
        ),
        migrations.AddIndex(
            model_name='airqualityforecast',
            index=models.Index(fields=['date'], name='myapp_airqu_date_c9bcaa_idx'),
        ),
        migrations.AddIndex(
            model_name='airqualityforecast',
            index=models.Index(fields=['gas_type'], name='myapp_airqu_gas_typ_6b77de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='airqualityforecast',
            unique_together={('date', 'gas_type')},
        ),
        migrations.AddConstraint(
            model_name='healthassessment',
            constraint=models.UniqueConstraint(fields=('user',), name='health_assessment_user_id_key'),
        ),
        migrations.AddConstraint(
            model_name='healthassessment',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='health_assessment_phone_number_key'),
        ),
    ]
