# Generated by Django 5.2.1 on 2025-07-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.FloatField(null=True)),
                ('nh3', models.FloatField(null=True)),
                ('no2', models.FloatField(null=True)),
                ('o3', models.FloatField(null=True)),
                ('pm25', models.FloatField(null=True)),
                ('pm10', models.FloatField(null=True)),
                ('so2', models.FloatField(null=True)),
                ('hum', models.FloatField(null=True)),
                ('temp', models.FloatField(null=True)),
                ('pre', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('aqi', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gas_type', models.CharField(max_length=20)),
                ('forecasted_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='myapp_airqu_date_c9bcaa_idx'), models.Index(fields=['gas_type'], name='myapp_airqu_gas_typ_6b77de_idx')],
                'unique_together': {('date', 'gas_type')},
            },
        ),
        migrations.CreateModel(
            name='HealthQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('relationship', models.CharField(max_length=50)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('respiratory_conditions', models.JSONField(default=list)),
                ('smoking_history', models.TextField()),
                ('living_environment', models.JSONField(default=list)),
                ('common_symptoms', models.JSONField(default=list)),
                ('occupational_exposure', models.CharField(max_length=50)),
                ('medical_history', models.JSONField(default=list)),
                ('health_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', unique=True)),
            ],
            options={
                'verbose_name': 'Health Assessment',
                'verbose_name_plural': 'Health Assessments',
                'indexes': [models.Index(fields=['health_score'], name='myapp_healt_health__2f1c18_idx'), models.Index(fields=['created_at'], name='myapp_healt_created_074a29_idx'), models.Index(fields=['user'], name='myapp_healt_user_id_dc42e1_idx')],
            },
        ),
    ]
