# Generated by Django 4.2 on 2026-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopevent',
            name='category',
            field=models.CharField(choices=[('Hands-on-Workshop', 'Hands-on Workshop'), ('Summer Internship', 'Summer Internship'), ('Value Added Course', 'Value Added Course'), ('Workshop', 'Workshop'), ('Research', 'Research'), ('Winter Internship', 'Winter Internship'), ('Internship', 'Internship'), ('Hackathon', 'Hackathon'), ('Idea pitching', 'Idea Pitching')], default='Workshop', max_length=50),
        ),
    ]
