# Generated by Django 4.2 on 2025-08-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMemberHealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('respiratory_conditions', models.JSONField(default=list)),
                ('smoking_history', models.TextField()),
                ('living_environment', models.JSONField(default=list)),
                ('common_symptoms', models.JSONField(default=list)),
                ('occupational_exposure', models.CharField(max_length=50)),
                ('medical_history', models.JSONField(default=list)),
                ('health_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_assessment', to='myapp.familymembers')),
            ],
        ),
    ]
