# Generated by Django 4.2 on 2025-08-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_familymemberhealthassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMemberHealthAssessment',
        ),
    ]
