# Generated by Django 4.2 on 2025-11-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup_userlogin_delete_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthassessment',
            options={'managed': False},
        ),
    ]
