# Generated by Django 4.2 on 2026-02-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_notification_table_alter_resource_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='brochure',
            table='brochure',
        ),
        migrations.AlterModelTable(
            name='familymembers',
            table='family_members',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='resourcefile',
            table='resource_file',
        ),
        migrations.AlterModelTable(
            name='workshopevent',
            table='workshop_event',
        ),
    ]
