# Generated by Django 4.2 on 2025-11-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_healthassessment_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='healthassessment',
            table='health_assessment',
        ),
    ]
