# Generated by Django 4.2 on 2025-11-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_healthassessment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('sl_no', models.AutoField(db_column='sl_no', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='submitted_at')),
            ],
            options={
                'db_table': 'support',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('brochure', 'Brochure'), ('poster', 'Poster'), ('slide', 'Slide'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
