# Generated by Django 4.2 on 2025-11-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_support_resourcefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirQualityData',
        ),
    ]
