# Generated by Django 4.2 on 2025-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('center', 'Center Brochure'), ('vision', 'Vision & Mission'), ('setup', 'Setup Guide'), ('report', 'Annual Report')], max_length=50)),
                ('file', models.FileField(upload_to='brochures/%Y/%m/%d/')),
                ('icon', models.CharField(default='📄', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
