# Generated by Django 4.2 on 2025-11-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('brochure', 'Brochure'), ('poster', 'Poster'), ('slide', 'Slide'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthquestionnaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.signup'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/%Y/%m/%d/'),
        ),
    ]
