# Generated by Django 4.2 on 2025-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_resource_category_alter_healthquestionnaire_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='category',
            field=models.CharField(choices=[('iot_internship', 'IoT Internship'), ('workshop', 'Workshop'), ('vision', 'Vision & Mission'), ('project', 'Student Projects'), ('research', 'Research & Publications')], max_length=50),
        ),
    ]
