# Generated by Django 4.2 on 2025-12-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_brochure_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date_text', models.CharField(max_length=100)),
                ('participants', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('brochure_file', models.FileField(blank=True, null=True, upload_to='workshops/brochures/')),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('internship', 'Internship'), ('research', 'Research & Output')], default='workshop', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
