# Generated by Django 4.2 on 2025-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_workshopevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL identifier like 'indoor-monitor'", max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Air Quality', 'Air Quality'), ('Water Solutions', 'Water Solutions'), ('Weather', 'Weather'), ('Training', 'Training')], default='Air Quality', max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('features', models.JSONField(default=list, help_text="List of features ['Feature 1', 'Feature 2']")),
                ('specs', models.JSONField(default=dict, help_text="Dictionary of specs {'Range': '10km', 'Power': '5V'}")),
            ],
        ),
    ]
