# Generated by Django 4.2 on 2025-12-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_productspecification_productfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='products/brochures/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/sub/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/hero/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text="Unique URL ID (e.g. 'indoor-monitor')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='icon',
            field=models.CharField(default='⚡', help_text='Paste an Emoji here', max_length=50),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='myapp.product'),
        ),
    ]
