# Generated by Django 4.2 on 2025-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_product_features_remove_product_specs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workshopevent',
            name='brochure_file',
        ),
        migrations.AddField(
            model_name='workshopevent',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g. '1 Day'", max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='category',
            field=models.CharField(choices=[('Hands-on-Workshop', 'Hands-on Workshop'), ('Summer Internship', 'Summer Internship'), ('Value Added Course', 'Value Added Course'), ('Workshop', 'Workshop'), ('Research', 'Research')], default='Workshop', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
