# Generated by Django 4.2 on 2025-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_resource_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopevent',
            name='brochure_file',
            field=models.FileField(blank=True, null=True, upload_to='workshops/brochures/'),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g. '1 Day', '15 Days'", max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='event_date_text',
            field=models.CharField(help_text="e.g. 'March 19, 2025'", max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='participants',
            field=models.CharField(blank=True, help_text="e.g. '40 Participants'", max_length=50),
        ),
    ]
