# Generated by Django 4.2 on 2026-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_workshopevent_brochure_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='The text to display in the scroll bar', max_length=255)),
                ('start_date', models.DateTimeField(help_text='When to start showing this message')),
                ('end_date', models.DateTimeField(help_text='When to stop showing this message')),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Check this for annual events (e.g., Independence Day). The year will be ignored.')),
                ('link', models.CharField(blank=True, help_text='Optional link to a registration page or brochure', max_length=255, null=True)),
            ],
        ),
    ]
