# Generated by Django 4.2 on 2026-05-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(default='N/A', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('station_id', models.CharField(db_index=True, max_length=100)),
                ('data_parameters', models.JSONField(blank=True, default=list, help_text='List of requested parameters')),
                ('purpose', models.TextField(default='N/A')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin approval/rejection notes')),
            ],
            options={
                'verbose_name': 'Data Request',
                'verbose_name_plural': 'Data Requests',
                'ordering': ['-request_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('station_name', models.CharField(default='Unknown Station', max_length=255)),
                ('station_type', models.CharField(choices=[('V1', 'Old V1 Station'), ('V2', 'New V2 Station')], default='V2', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Station',
                'verbose_name_plural': 'Weather Stations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity %', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Air Pressure hPa', null=True)),
                ('wind_speed_kph', models.FloatField(blank=True, help_text='Wind Speed km/h', null=True)),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind Direction degrees', null=True)),
                ('rain_1h_mm', models.FloatField(blank=True, help_text='Rainfall 1h mm', null=True)),
                ('rain_24h_mm', models.FloatField(blank=True, help_text='Rainfall 24h mm', null=True)),
                ('server_time', models.CharField(blank=True, help_text='Server Time DD:MM:YYYY:HH:MM', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('dynamodb_timestamp', models.CharField(blank=True, help_text='DynamoDB received_at', max_length=100)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='weather_monitoring.weatherstation')),
            ],
            options={
                'verbose_name': 'Weather Reading',
                'verbose_name_plural': 'Weather Readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datarequest',
            index=models.Index(fields=['status', '-request_timestamp'], name='weather_mon_status_91854f_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherreading',
            index=models.Index(fields=['station', '-recorded_at'], name='weather_mon_station_cc9505_idx'),
        ),
    ]
